import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar สร้างอัตโนมัติจากโครงโฟลเดอร์ใน docs/
 *
 * ลำดับของบทมาจาก **เลขนำหน้าชื่อไฟล์** เท่านั้น (เช่น 02-world-of-zero-and-one.mdx)
 * ห้ามใส่ sidebar_position ในบทเรียน — จะกลายเป็นสองแหล่งความจริงที่ขัดกันเอง
 * (ดู CLAUDE.md หัวข้อ 7)
 */
const sidebars: SidebarsConfig = {
  courseSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
